export const enum Material {
  Empty = 0,
  Sand = 1,
  Water = 2,
  Wall = 3,
  Fire = 4,
  Smoke = 5,
  Dust = 6,
  Salt = 7,
  Oil = 8,
  Wood = 9,
  Plant = 10,
  Lava = 11,
  Ice = 12,
  Acid = 13,
  Gunpowder = 14,
  // Native reaction products. These IDs are part of the rendering ABI but are
  // intentionally omitted from MATERIALS, so they do not become brush tools.
  Steam = 15,
  SaltWater = 16,
  Gas = 17,
  Snow = 18,
  Coal = 19,
  Plasma = 20,
  Stone = 21,
  Brick = 22,
  Metal = 23,
  Glass = 24,
  Ceramic = 25,
  Concrete = 26,
  Wax = 27,
  Clay = 28,
  Quartz = 29,
  Thermite = 30,
  C4 = 31,
  Nitro = 32,
  Firework = 33,
  DistilledWater = 34,
  Diesel = 35,
  Mercury = 36,
  LiquidNitrogen = 37,
  Soap = 38,
  Oxygen = 39,
  Hydrogen = 40,
  CarbonDioxide = 41,
  NobleGas = 42,
  ANAR = 43,
  BGLA = 44,
  BREC = 45,
  BRMT = 46,
  FRZZ = 47,
  GRAV = 48,
  SAWD = 49,
  SEED = 50,
  SLCN = 51,
  YEST = 52,
  BASE = 53,
  BIZR = 54,
  CBNW = 55,
  GEL = 56,
  GLOW = 57,
  LO2 = 58,
  MWAX = 59,
  PSTE = 60,
  RSST = 61,
  VIRS = 62,
  BOYL = 63,
  CAUS = 64,
  FOG = 65,
  RFRG = 66,
  BMTL = 67,
  DRIC = 68,
  FILT = 69,
  GOLD = 70,
  GOO = 71,
  HEAC = 72,
  IRON = 73,
  NICE = 74,
  PTNM = 75,
  QRTZ = 76,
  RIME = 77,
  ROCK = 78,
  RSSS = 79,
  SHLD1 = 80,
  SPNG = 81,
  TTAN = 82,
  VINE = 83,
  BANG = 84,
  BOMB = 85,
  C5 = 86,
  CFLM = 87,
  DEST = 88,
  FIRW = 89,
  FSEP = 90,
  FUSE = 91,
  IGNT = 92,
  LIGH = 93,
  LITH = 94,
  LRBD = 95,
  RBDM = 96,
  THDR = 97,
  AMTR = 98,
  BVBR = 99,
  DEUT = 100,
  ELEC = 101,
  EXOT = 102,
  GRVT = 103,
  ISOZ = 104,
  ISZS = 105,
  NEUT = 106,
  PHOT = 107,
  PLUT = 108,
  POLO = 109,
  PROT = 110,
  SING = 111,
  URAN = 112,
  VIBR = 113,
  WARP = 114,
  ACEL = 115,
  DCEL = 116,
  DMG = 117,
  FRAY = 118,
  FRME = 119,
  GBMB = 120,
  PIPE = 121,
  PSTN = 122,
  RPEL = 123,
  BCLN = 124,
  BHOL = 125,
  CLNE = 126,
  CONV = 127,
  NBHL = 128,
  NWHL = 129,
  PRTI = 130,
  PRTO = 131,
  TRON = 132,
  VOID = 133,
  WHOL = 134,
  ARAY = 135,
  BTRY = 136,
  CRAY = 137,
  DRAY = 138,
  EMP = 139,
  ETRD = 140,
  INSL = 141,
  INST = 142,
  INWR = 143,
  NSCN = 144,
  NTCT = 145,
  PSCN = 146,
  PTCT = 147,
  SPRK = 148,
  SWCH = 149,
  TESC = 150,
  TUNG = 151,
  WIFI = 152,
  WIRE = 153,
  DLAY = 154,
  GPMP = 155,
  HSWC = 156,
  LCRY = 157,
  PBCN = 158,
  PCLN = 159,
  PPIP = 160,
  PUMP = 161,
  PVOD = 162,
  STOR = 163,
  DTEC = 164,
  INVIS = 165,
  LDTC = 166,
  LSNS = 167,
  PSNS = 168,
  TSNS = 169,
  VSNS = 170,
}

export type MaterialCategory = 'powders' | 'liquids' | 'solids' | 'gases' | 'energy' | 'explosives' | 'special' | 'radioactive' | 'force' | 'electronics' | 'powered' | 'sensors' | 'life';

export type NativeLimitation = 'newtonian-gravity-unavailable' | 'air-velocity-limited';

export interface MaterialInfo {
  readonly id: Material;
  readonly name: string;
  readonly description: string;
  readonly color: string;
  readonly icon: string;
  readonly category: MaterialCategory;
  readonly selectable: boolean;
  readonly hazard?: 'caution' | 'danger';
  readonly available?: boolean;
  readonly limitations?: readonly NativeLimitation[];
}

export const ALL_MATERIALS: readonly MaterialInfo[] = [
  { id: Material.Sand, name: 'Sand', description: 'Pours and settles', color: '#d7aa68', icon: '●', category: 'powders', selectable: true },
  { id: Material.Water, name: 'Water', description: 'Flows into spaces', color: '#5cb9c8', icon: '●', category: 'liquids', selectable: true },
  { id: Material.Wall, name: 'Diamond', description: 'Indestructible walls', color: '#8b8174', icon: '■', category: 'solids', selectable: true },
  { id: Material.Fire, name: 'Fire', description: 'Ignites flammable materials', color: '#ff8052', icon: '◆', category: 'energy', selectable: true },
  { id: Material.Smoke, name: 'Smoke', description: 'Drifts upward', color: '#9d9891', icon: '○', category: 'gases', selectable: true },
  { id: Material.Dust, name: 'Dust', description: 'Light flammable powder', color: '#c9b58d', icon: '·', category: 'powders', selectable: true },
  { id: Material.Salt, name: 'Salt', description: 'Crystals that dissolve', color: '#eee6d5', icon: '✦', category: 'powders', selectable: true },
  { id: Material.Oil, name: 'Oil', description: 'Flammable liquid', color: '#8f7040', icon: '●', category: 'liquids', selectable: true },
  { id: Material.Wood, name: 'Wood', description: 'A combustible solid', color: '#9b6038', icon: '▥', category: 'life', selectable: true },
  { id: Material.Plant, name: 'Plant', description: 'Drinks water and grows', color: '#65a95f', icon: '✳', category: 'life', selectable: true },
  { id: Material.Lava, name: 'Lava', description: 'Molten and intensely hot', color: '#ff4d21', icon: '◆', category: 'liquids', selectable: true },
  { id: Material.Ice, name: 'Ice', description: 'Frozen water', color: '#a7e5ec', icon: '◇', category: 'solids', selectable: true },
  { id: Material.Acid, name: 'Acid', description: 'Corrodes many materials', color: '#d35ee8', icon: '●', category: 'liquids', selectable: true },
  { id: Material.Gunpowder, name: 'Gunpowder', description: 'Explodes when ignited', color: '#5d554d', icon: '⁙', category: 'explosives', selectable: true },
  { id: Material.Steam, name: 'Steam', description: 'Hot water vapour', color: '#b9dce2', icon: '○', category: 'gases', selectable: false },
  { id: Material.SaltWater, name: 'Salt Water', description: 'Conductive saline water', color: '#5c9fb6', icon: '●', category: 'liquids', selectable: false },
  { id: Material.Gas, name: 'Gas', description: 'Flammable hydrocarbon gas', color: '#c6b35d', icon: '○', category: 'gases', selectable: false },
  { id: Material.Snow, name: 'Snow', description: 'Powdered ice', color: '#e4f5f7', icon: '·', category: 'powders', selectable: false },
  { id: Material.Coal, name: 'Coal', description: 'Slow-burning carbon', color: '#2d2926', icon: '■', category: 'solids', selectable: true },
  { id: Material.Plasma, name: 'Plasma', description: 'Extremely hot ionized gas', color: '#d879ff', icon: '◆', category: 'energy', selectable: false },
  { id: Material.Stone, name: 'Stone', description: 'Heavy breakable stone', color: '#77736d', icon: '■', category: 'powders', selectable: true },
  { id: Material.Brick, name: 'Brick', description: 'Rigid breakable brick', color: '#a65e4b', icon: '▦', category: 'solids', selectable: true },
  { id: Material.Metal, name: 'Metal', description: 'Conductive meltable solid', color: '#667086', icon: '■', category: 'solids', selectable: true },
  { id: Material.Glass, name: 'Glass', description: 'Transparent pressure-resistant solid', color: '#b9d8d2', icon: '□', category: 'solids', selectable: true },
  { id: Material.Ceramic, name: 'Ceramic', description: 'Heat-resistant brittle solid', color: '#d8d0be', icon: '■', category: 'solids', selectable: true },
  { id: Material.Concrete, name: 'Concrete', description: 'Heavy structural powder', color: '#86837d', icon: '⁙', category: 'powders', selectable: true },
  { id: Material.Wax, name: 'Wax', description: 'Melts and burns', color: '#e0c278', icon: '■', category: 'solids', selectable: true },
  { id: Material.Clay, name: 'Clay', description: 'Wettable clay dust', color: '#b87955', icon: '·', category: 'powders', selectable: true },
  { id: Material.Quartz, name: 'Quartz', description: 'Pressure-sensitive crystal powder', color: '#d8b0c2', icon: '✦', category: 'powders', selectable: true },
  { id: Material.Thermite, name: 'Thermite', description: 'Burns into molten metal', color: '#9f4b32', icon: '⁙', category: 'explosives', selectable: true },
  { id: Material.C4, name: 'C-4', description: 'Pressure-sensitive explosive', color: '#c8c4a6', icon: '⁙', category: 'explosives', selectable: true },
  { id: Material.Nitro, name: 'Nitro', description: 'Explosive liquid', color: '#b7a66a', icon: '●', category: 'explosives', selectable: true },
  { id: Material.Firework, name: 'Firework', description: 'Colourful explosive powder', color: '#9c72c7', icon: '✦', category: 'explosives', selectable: true },
  { id: Material.DistilledWater, name: 'Distilled', description: 'Pure non-conductive water', color: '#75cfdf', icon: '●', category: 'liquids', selectable: true },
  { id: Material.Diesel, name: 'Diesel', description: 'Combustible liquid fuel', color: '#9b7d3d', icon: '●', category: 'liquids', selectable: true },
  { id: Material.Mercury, name: 'Mercury', description: 'Dense conductive liquid metal', color: '#a8afba', icon: '●', category: 'liquids', selectable: true },
  { id: Material.LiquidNitrogen, name: 'Liquid N₂', description: 'Cryogenic liquid', color: '#9bdaf2', icon: '●', category: 'liquids', selectable: true },
  { id: Material.Soap, name: 'Soap', description: 'Forms bubbles in water', color: '#a8d8bc', icon: '●', category: 'liquids', selectable: true },
  { id: Material.Oxygen, name: 'Oxygen', description: 'Supports combustion', color: '#80b8e8', icon: '○', category: 'gases', selectable: true },
  { id: Material.Hydrogen, name: 'Hydrogen', description: 'Light explosive gas', color: '#e4e0d5', icon: '○', category: 'gases', selectable: true },
  { id: Material.CarbonDioxide, name: 'CO₂', description: 'Suppresses fire', color: '#8d9293', icon: '○', category: 'gases', selectable: true },
  { id: Material.NobleGas, name: 'Noble Gas', description: 'Glows when electrically charged', color: '#c277d7', icon: '○', category: 'gases', selectable: true },
  { id: Material.ANAR, name: 'ANAR', description: 'Anti-air. Very light gravity-defying dust. Burns cold instead of hot.', color: '#ffffee', icon: '·', category: 'powders', selectable: true },
  { id: Material.BGLA, name: 'BGLA', description: 'Broken Glass, heavy particles formed when glass breaks under pressure. Meltable. Bagels.', color: '#606060', icon: '·', category: 'powders', selectable: true },
  { id: Material.BREC, name: 'BREL', description: 'Broken electronics. Formed from EMP blasts, and when constantly sparked while under pressure, turns to EXOT.', color: '#707060', icon: '·', category: 'powders', selectable: true },
  { id: Material.BRMT, name: 'BRMT', description: 'Broken metal. Created when iron rusts or when metals break from pressure.', color: '#705060', icon: '·', category: 'powders', selectable: true },
  { id: Material.FRZZ, name: 'FRZZ', description: 'Freeze powder. When melted, forms ice that always cools. Spreads with regular water.', color: '#c0e0ff', icon: '·', category: 'powders', selectable: true },
  { id: Material.GRAV, name: 'GRAV', description: 'Very light dust. Changes colour based on velocity.', color: '#202020', icon: '·', category: 'powders', selectable: true },
  { id: Material.SAWD, name: 'SAWD', description: 'Sawdust. Floats on water.', color: '#f0f0a0', icon: '·', category: 'powders', selectable: true },
  { id: Material.SEED, name: 'SEED', description: 'Seeds. Put on sand and add water to grow a tree.', color: '#88e788', icon: '·', category: 'life', selectable: true },
  { id: Material.SLCN, name: 'SLCN', description: 'Powdered Silicon. A key ingredient in producing multiple materials.', color: '#bccddf', icon: '·', category: 'powders', selectable: true },
  { id: Material.YEST, name: 'YEST', description: 'Yeast, grows when warm (~37C).', color: '#eee0c0', icon: '·', category: 'life', selectable: true },
  { id: Material.BASE, name: 'BASE', description: 'Corrosive liquid. Rusts conductive solids, neutralizes acid.', color: '#90d5ff', icon: '●', category: 'liquids', selectable: true },
  { id: Material.BIZR, name: 'BIZR', description: 'Bizarre... contradicts the normal state changes. Paints other elements with its deco color.', color: '#00ff77', icon: '●', category: 'liquids', selectable: true },
  { id: Material.CBNW, name: 'BUBW', description: 'Carbonated water. Slowly releases CO2.', color: '#2030d0', icon: '●', category: 'liquids', selectable: true },
  { id: Material.GEL, name: 'GEL', description: 'A liquid with variable viscosity and heat conductivity. Absorbs water.', color: '#ff9900', icon: '●', category: 'liquids', selectable: true },
  { id: Material.GLOW, name: 'GLOW', description: 'Glow, Glows under pressure.', color: '#445464', icon: '●', category: 'liquids', selectable: true },
  { id: Material.LO2, name: 'LOXY', description: 'Liquid Oxygen. Very cold. Reacts with fire.', color: '#80a0ef', icon: '●', category: 'liquids', selectable: true },
  { id: Material.MWAX, name: 'MWAX', description: 'Liquid Wax. Hardens into WAX at 45 degrees.', color: '#e0e0aa', icon: '●', category: 'liquids', selectable: true },
  { id: Material.PSTE, name: 'PSTE', description: 'Colloid, Hardens under pressure.', color: '#aa99aa', icon: '●', category: 'liquids', selectable: true },
  { id: Material.RSST, name: 'RSST', description: 'Resist. Solidifies on contact with photons, is destroyed by electrons and spark.', color: '#f95b49', icon: '●', category: 'liquids', selectable: true },
  { id: Material.VIRS, name: 'VIRS', description: 'Virus. Turns everything it touches into virus.', color: '#fe11f6', icon: '●', category: 'liquids', selectable: true },
  { id: Material.BOYL, name: 'BOYL', description: 'Boyle, variable pressure gas. Expands when heated.', color: '#0a3200', icon: '○', category: 'gases', selectable: true },
  { id: Material.CAUS, name: 'CAUS', description: 'Caustic Gas, acts like ACID.', color: '#80ffa0', icon: '○', category: 'gases', selectable: true },
  { id: Material.FOG, name: 'FOG', description: 'Fog, created when an electric current is passed through RIME.', color: '#aaaaaa', icon: '○', category: 'gases', selectable: true },
  { id: Material.RFRG, name: 'RFRG', description: 'Refrigerant. Heats up and liquefies under pressure.', color: '#72d2d4', icon: '○', category: 'gases', selectable: true },
  { id: Material.BMTL, name: 'BMTL', description: 'Breakable metal. Common conductive building material, can melt and break under pressure.', color: '#505070', icon: '■', category: 'solids', selectable: true },
  { id: Material.DRIC, name: 'DRIC', description: 'Dry Ice, formed when CO2 is cooled.', color: '#e0e0e0', icon: '■', category: 'solids', selectable: true },
  { id: Material.FILT, name: 'FILT', description: 'Filter. Changes color of PHOT and BIZR. Color depends on temperature.', color: '#000056', icon: '■', category: 'solids', selectable: true },
  { id: Material.GOLD, name: 'GOLD', description: 'Corrosion resistant metal, will reverse corrosion of iron. Excellent conductor.', color: '#dcad2c', icon: '■', category: 'solids', selectable: true },
  { id: Material.GOO, name: 'GOO', description: 'Deforms and disappears under pressure.', color: '#804000', icon: '■', category: 'solids', selectable: true },
  { id: Material.HEAC, name: 'HEAC', description: 'Rapid heat conductor.', color: '#cb6351', icon: '■', category: 'solids', selectable: true },
  { id: Material.IRON, name: 'IRON', description: 'Rusts with salt, can be used for electrolysis of WATR.', color: '#707070', icon: '■', category: 'solids', selectable: true },
  { id: Material.NICE, name: 'NICE', description: 'Nitrogen Ice. Very cold, will melt into LN2 when heated only slightly.', color: '#c0e0ff', icon: '■', category: 'solids', selectable: true },
  { id: Material.PTNM, name: 'PTNM', description: 'Platinum. Catalyzes certain reactions.', color: '#d5e0eb', icon: '■', category: 'solids', selectable: true },
  { id: Material.QRTZ, name: 'QRTZ', description: 'Quartz, breakable mineral. Conducts but becomes brittle when cold. Scatters photons.', color: '#aadddd', icon: '■', category: 'solids', selectable: true },
  { id: Material.RIME, name: 'RIME', description: 'Solid, created when steam cools rapidly and goes through deposition, skipping the liquid phase.', color: '#cccccc', icon: '■', category: 'solids', selectable: true },
  { id: Material.ROCK, name: 'ROCK', description: 'Solid, melts into various elements.', color: '#727272', icon: '■', category: 'solids', selectable: true },
  { id: Material.RSSS, name: 'RSSS', description: 'Solidified resist. Blocks pressure and insulates electricity. Liquefies on contact with neutrons.', color: '#c43626', icon: '■', category: 'solids', selectable: true },
  { id: Material.SHLD1, name: 'SHLD', description: 'Shield. Grows around spark, broken by pressure.', color: '#aaaaaa', icon: '■', category: 'solids', selectable: true },
  { id: Material.SPNG, name: 'SPNG', description: 'Sponge, absorbs water. Is not a moving solid.', color: '#ffbe30', icon: '■', category: 'solids', selectable: true },
  { id: Material.TTAN, name: 'TTAN', description: 'Titanium. Higher melting temperature than most other metals, blocks all air pressure.', color: '#909090', icon: '■', category: 'solids', selectable: true },
  { id: Material.VINE, name: 'VINE', description: 'Vine, can grow along WOOD.', color: '#079a00', icon: '■', category: 'life', selectable: true },
  { id: Material.BANG, name: 'TNT', description: 'TNT, explodes all at once.', color: '#c05050', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.BOMB, name: 'BOMB', description: 'Bomb. Explodes and destroys all surrounding particles when it touches something.', color: '#fff288', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.C5, name: 'C-5', description: 'Cold explosive, set off by anything cold.', color: '#2050e0', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.CFLM, name: 'CFLM', description: 'Sub-zero flame.', color: '#8080ff', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.DEST, name: 'DEST', description: 'More destructive Bomb, can break through virtually anything.', color: '#ff3311', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.FIRW, name: 'FIRW', description: 'Fireworks! Colorful, set off by fire.', color: '#ffa040', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.FSEP, name: 'FSEP', description: 'Fuse Powder. Burns slowly like FUSE.', color: '#63ad5f', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.FUSE, name: 'FUSE', description: 'Burns slowly. Ignites at very high temperatures or when sparked.', color: '#0a5706', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.IGNT, name: 'IGNC', description: 'Ignition cord. Burns slowly with fire and sparks.', color: '#c0b050', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.LIGH, name: 'LIGH', description: 'Lightning. Change the brush size to set the size of the lightning.', color: '#ffffc0', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.LITH, name: 'LITH', description: 'Lithium. Reactive element that explodes on contact with water.', color: '#b6aabf', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.LRBD, name: 'LRBD', description: 'Liquid Rubidium.', color: '#aaaaaa', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.RBDM, name: 'RBDM', description: 'Rubidium. Explosive, especially on contact with water. Low melting point.', color: '#cccccc', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.THDR, name: 'THDR', description: 'Lightning! Very hot, inflicts damage upon most materials, and transfers current to metals.', color: '#ffffa0', icon: '⁙', category: 'explosives', selectable: true, hazard: 'danger' },
  { id: Material.AMTR, name: 'AMTR', description: 'Anti-Matter, destroys a majority of particles.', color: '#808080', icon: '◆', category: 'radioactive', selectable: true, hazard: 'danger' },
  { id: Material.BVBR, name: 'BVBR', description: 'Broken vibranium.', color: '#005000', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.DEUT, name: 'DEUT', description: 'Deuterium oxide. Gets more concentrated when cold, explodes with neutrons or protons.', color: '#00153f', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.ELEC, name: 'ELEC', description: 'Electrons. Sparks electronics, reacts with NEUT and WATR.', color: '#dfefff', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.EXOT, name: 'EXOT', description: 'Exotic matter. Explodes with excess exposure to electrons. Has many other odd reactions.', color: '#247bfe', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.GRVT, name: 'GRVT', description: 'Gravitons. Create Newtonian Gravity.', color: '#00ee76', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution', available: false, limitations: ['newtonian-gravity-unavailable'] },
  { id: Material.ISOZ, name: 'ISOZ', description: 'Isotope-Z. Radioactive liquid, decays into photons when touching PHOT or under negative pressure.', color: '#aa30d0', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.ISZS, name: 'ISZS', description: 'Solid form of ISOZ, slowly decays into PHOT.', color: '#662089', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.NEUT, name: 'NEUT', description: 'Neutrons. Interact with matter in odd ways.', color: '#20e0ff', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.PHOT, name: 'PHOT', description: 'Photons. Refract through glass, and different elements change its color. Can ignite flammable materials.', color: '#ffffff', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.PLUT, name: 'PLUT', description: 'Plutonium. Heavy, fissile particles. Generates neutrons under pressure.', color: '#407020', icon: '◆', category: 'radioactive', selectable: true, hazard: 'danger' },
  { id: Material.POLO, name: 'POLO', description: 'Polonium, highly radioactive. Decays into NEUT and heats up.', color: '#506030', icon: '◆', category: 'radioactive', selectable: true, hazard: 'danger' },
  { id: Material.PROT, name: 'PROT', description: 'Protons. Transfer heat to materials, and remove sparks.', color: '#990000', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.SING, name: 'SING', description: 'Singularity. Creates huge amounts of negative pressure and destroys everything.', color: '#242424', icon: '◆', category: 'radioactive', selectable: true, hazard: 'danger' },
  { id: Material.URAN, name: 'URAN', description: 'Uranium. Heavy particles. Generates heat under pressure.', color: '#707020', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.VIBR, name: 'VIBR', description: 'Vibranium. Stores energy and releases it in violent explosions.', color: '#005000', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.WARP, name: 'WARP', description: 'Displaces other elements.', color: '#101010', icon: '◆', category: 'radioactive', selectable: true, hazard: 'caution' },
  { id: Material.ACEL, name: 'ACEL', description: 'Accelerator, speeds up nearby elements.', color: '#0099cc', icon: '➜', category: 'force', selectable: true },
  { id: Material.DCEL, name: 'DCEL', description: 'Decelerator, slows down nearby elements.', color: '#99cc00', icon: '➜', category: 'force', selectable: true },
  { id: Material.DMG, name: 'DMG', description: 'Generates damaging pressure and breaks any elements it hits.', color: '#88ff88', icon: '➜', category: 'force', selectable: true, hazard: 'danger' },
  { id: Material.FRAY, name: 'FRAY', description: 'Force Emitter. Pushes or pulls objects based on its temperature. Use like ARAY.', color: '#00bbff', icon: '➜', category: 'force', selectable: true },
  { id: Material.FRME, name: 'FRME', description: 'Frame, can be used with pistons to push many particles.', color: '#999988', icon: '➜', category: 'force', selectable: true },
  { id: Material.GBMB, name: 'GBMB', description: 'Gravity bomb. Sticks to the first object it touches then produces a strong gravity push.', color: '#1144bb', icon: '➜', category: 'force', selectable: true, hazard: 'danger', available: false, limitations: ['newtonian-gravity-unavailable'] },
  { id: Material.PIPE, name: 'PIPE', description: 'PIPE, moves particles around. Once the BRCK generates, erase some for the exit. Then the PIPE generates and is usable.', color: '#444444', icon: '➜', category: 'force', selectable: true },
  { id: Material.PSTN, name: 'PSTN', description: 'Piston, pushes particles. PSCN extends, NSCN retracts', color: '#aa9999', icon: '➜', category: 'force', selectable: true },
  { id: Material.RPEL, name: 'RPEL', description: 'Repels or attracts particles based on its temperature.', color: '#99cc00', icon: '➜', category: 'force', selectable: true },
  { id: Material.BCLN, name: 'BCLN', description: 'Breakable Clone.', color: '#ffd040', icon: '◇', category: 'special', selectable: true },
  { id: Material.BHOL, name: 'VACU', description: 'Vacuum, sucks in other particles and heats up.', color: '#303030', icon: '◇', category: 'special', selectable: true, hazard: 'danger' },
  { id: Material.CLNE, name: 'CLNE', description: 'Clone. Duplicates any particles it touches.', color: '#ffd010', icon: '◇', category: 'special', selectable: true },
  { id: Material.CONV, name: 'CONV', description: 'Converter. Converts everything into whatever it first touches.', color: '#0aab0a', icon: '◇', category: 'special', selectable: true },
  { id: Material.NBHL, name: 'BHOL', description: 'Black hole, sucks in particles using gravity. (Requires Newtonian gravity)', color: '#202020', icon: '◇', category: 'special', selectable: true, hazard: 'danger', available: false, limitations: ['newtonian-gravity-unavailable'] },
  { id: Material.NWHL, name: 'WHOL', description: 'White hole, pushes away other particles with gravity. (Requires Newtonian gravity)', color: '#ffffff', icon: '◇', category: 'special', selectable: true, hazard: 'danger', available: false, limitations: ['newtonian-gravity-unavailable'] },
  { id: Material.PRTI, name: 'PRTI', description: 'Portal IN. Particles go in here. Also has temperature dependent channels. (same as WIFI)', color: '#eb5917', icon: '◇', category: 'special', selectable: true },
  { id: Material.PRTO, name: 'PRTO', description: 'Portal OUT. Particles come out here. Also has temperature dependent channels. (same as WIFI)', color: '#0020eb', icon: '◇', category: 'special', selectable: true },
  { id: Material.TRON, name: 'TRON', description: 'Smart particles, Travels in straight lines and avoids obstacles. Grows with time.', color: '#a9ff00', icon: '◇', category: 'special', selectable: true },
  { id: Material.VOID, name: 'VOID', description: 'Hole, will drain away any particles.', color: '#790b0b', icon: '◇', category: 'special', selectable: true, hazard: 'danger' },
  { id: Material.WHOL, name: 'VENT', description: 'Air vent, creates pressure and pushes other particles away.', color: '#efefef', icon: '◇', category: 'special', selectable: true, limitations: ['air-velocity-limited'] },
  { id: Material.ARAY, name: 'ARAY', description: 'Ray Emitter. Rays create points when they collide.', color: '#ffbb00', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.BTRY, name: 'BTRY', description: 'Battery. Generates infinite electricity.', color: '#858505', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.CRAY, name: 'CRAY', description: 'Particle Ray Emitter. Creates a beam of particles set by its ctype, with a range set by tmp.', color: '#bbff00', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.DRAY, name: 'DRAY', description: 'Duplicator ray. Replicates a line of particles in front of it.', color: '#ffaa22', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.EMP, name: 'EMP', description: 'Electromagnetic pulse. Breaks activated electronics.', color: '#66aaff', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.ETRD, name: 'ETRD', description: 'Electrode. Creates plasma arcs with electricity. (Use sparingly)', color: '#404040', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.INSL, name: 'INSL', description: 'Insulator. Blocks heat, electricity, and radiation.', color: '#9ea3b6', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.INST, name: 'INST', description: 'Instantly conducts, PSCN to charge, NSCN to take.', color: '#404039', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.INWR, name: 'INWR', description: 'Insulated wire. Only conducts to PSCN, NSCN, WIFI, and SWCH.', color: '#544141', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.NSCN, name: 'NSCN', description: 'N-Type Silicon, Will not transfer current to P-Type Silicon. Disables powered materials.', color: '#505080', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.NTCT, name: 'NTCT', description: 'NTC Thermistor. Conducts with PSCN and NSCN, but only when heated above 100C.', color: '#505040', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.PSCN, name: 'PSCN', description: 'P-Type Silicon, Will transfer current to any conductor. Enables powered materials.', color: '#805050', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.PTCT, name: 'PTCT', description: 'PTC Thermistor. Conducts with PSCN and NSCN, but only when cooled below 100C.', color: '#405050', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.SPRK, name: 'SPRK', description: 'Electricity. The basis of all electronics in TPT, travels along conductive elements.', color: '#ffff80', icon: '⌁', category: 'electronics', selectable: true, hazard: 'caution' },
  { id: Material.SWCH, name: 'SWCH', description: 'Switch. Only conducts when switched on. (PSCN switches on, NSCN switches off)', color: '#103b11', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.TESC, name: 'TESC', description: 'Tesla coil! Creates lightning when sparked.', color: '#707040', icon: '⌁', category: 'electronics', selectable: true, hazard: 'danger' },
  { id: Material.TUNG, name: 'TUNG', description: 'Tungsten. Brittle metal with a very high melting point.', color: '#505050', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.WIFI, name: 'WIFI', description: 'Wireless transmitter, transfers spark to any other wifi on the same temperature channel.', color: '#40a060', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.WIRE, name: 'WWLD', description: 'WireWorld wires, conducts based on a set of GOL-like rules.', color: '#ffcc00', icon: '⌁', category: 'electronics', selectable: true },
  { id: Material.DLAY, name: 'DLAY', description: 'Conducts with temperature-dependent delay. (use HEAT/COOL).', color: '#753590', icon: '▣', category: 'powered', selectable: true },
  { id: Material.GPMP, name: 'GPMP', description: 'Gravity pump. Changes gravity to its temp when activated. (use HEAT/COOL)', color: '#0a3b3b', icon: '▣', category: 'powered', selectable: true, available: false, limitations: ['newtonian-gravity-unavailable'] },
  { id: Material.HSWC, name: 'HSWC', description: 'Heat switch. Conducts heat only when activated.', color: '#3b0a0a', icon: '▣', category: 'powered', selectable: true },
  { id: Material.LCRY, name: 'LCRY', description: 'Liquid Crystal. Changes colour when charged. (PSCN Charges, NSCN Discharges)', color: '#505050', icon: '▣', category: 'powered', selectable: true },
  { id: Material.PBCN, name: 'PBCN', description: 'Powered breakable clone.', color: '#3b1d0a', icon: '▣', category: 'powered', selectable: true },
  { id: Material.PCLN, name: 'PCLN', description: 'Powered clone. When activated, duplicates any particles it touches.', color: '#3b3b0a', icon: '▣', category: 'powered', selectable: true },
  { id: Material.PPIP, name: 'PPIP', description: 'Powered version of PIPE, use PSCN/NSCN to Activate/Deactivate.', color: '#444466', icon: '▣', category: 'powered', selectable: true },
  { id: Material.PUMP, name: 'PUMP', description: 'Pressure pump. Changes pressure to its temp when activated. (use HEAT/COOL).', color: '#0a0a3b', icon: '▣', category: 'powered', selectable: true },
  { id: Material.PVOD, name: 'PVOD', description: 'Powered VOID. When activated, destroys entering particles.', color: '#792020', icon: '▣', category: 'powered', selectable: true },
  { id: Material.STOR, name: 'STOR', description: 'Storage. Captures and stores a single particle. Releases when charged with PSCN, also passes to PIPE.', color: '#50dfdf', icon: '▣', category: 'powered', selectable: true },
  { id: Material.DTEC, name: 'DTEC', description: 'Detector, creates a spark when something with its ctype is nearby.', color: '#fd9d18', icon: '◉', category: 'sensors', selectable: true },
  { id: Material.INVIS, name: 'INVS', description: 'Invisible under pressure, allowing particles through.', color: '#00cccc', icon: '◉', category: 'sensors', selectable: true },
  { id: Material.LDTC, name: 'LDTC', description: 'Linear detector. Scans in 8 directions for particles with its ctype and creates a spark on the opposite side.', color: '#66ff66', icon: '◉', category: 'sensors', selectable: true },
  { id: Material.LSNS, name: 'LSNS', description: 'Life sensor, creates a spark when there\'s a nearby particle with a life higher than its temperature.', color: '#336699', icon: '◉', category: 'sensors', selectable: true },
  { id: Material.PSNS, name: 'PSNS', description: 'Pressure sensor, creates a spark when the pressure is greater than its temperature.', color: '#db2020', icon: '◉', category: 'sensors', selectable: true },
  { id: Material.TSNS, name: 'TSNS', description: 'Temperature sensor, creates a spark when there\'s a nearby particle with a greater temperature.', color: '#fd00d5', icon: '◉', category: 'sensors', selectable: true },
  { id: Material.VSNS, name: 'VSNS', description: 'Velocity sensor, creates a spark when there\'s a nearby particle with velocity higher than its temperature.', color: '#7c9c00', icon: '◉', category: 'sensors', selectable: true },

];

export const MATERIALS: readonly MaterialInfo[] = ALL_MATERIALS.filter(({ selectable }) => selectable);
