// Generated by scripts/visual-static-contract-declarations.mjs. Do not edit.
export declare const VISUAL_LAB_STATIC_CONTRACT: Readonly<{
  readonly "schema": "anifor.visual-lab.static-contract/v1";
  readonly "domainCodes": Readonly<{
    readonly "off": 0;
    readonly "powder": 1;
    readonly "liquid": 2;
    readonly "gas": 3;
    readonly "emission": 4;
  }>;
  readonly "domains": readonly [
    Readonly<{
      readonly "name": "off";
      readonly "code": 0;
      readonly "implemented": false;
      readonly "targetKind": "none";
      readonly "executionProfile": null;
      readonly "evidence": null;
      readonly "fixedUrlParameters": Readonly<Record<string, never>>;
    }>,
    Readonly<{
      readonly "name": "powder";
      readonly "code": 1;
      readonly "implemented": false;
      readonly "targetKind": "semantic-material-id";
      readonly "executionProfile": null;
      readonly "evidence": null;
      readonly "fixedUrlParameters": Readonly<Record<string, never>>;
    }>,
    Readonly<{
      readonly "name": "liquid";
      readonly "code": 2;
      readonly "implemented": true;
      readonly "targetKind": "semantic-material-id";
      readonly "executionProfile": Readonly<{
        readonly "detailScales": readonly [
          1,
          2,
          4,
        ];
        readonly "backend": "webgl";
        readonly "pipeline": "normal-hdr";
        readonly "variantZero": "pixel-preserving-baseline";
        readonly "fallbacks": Readonly<{
          readonly "classic": "disabled-preserve-baseline";
          readonly "canvas2d": "disabled-preserve-baseline";
          readonly "hdrUnavailable": "disabled-preserve-baseline";
          readonly "detail8x": "disabled-preserve-baseline";
        }>;
      }>;
      readonly "evidence": Readonly<{
        readonly "readerMethod": "liquidFieldAlpha";
        readonly "plane": "liquid-alpha";
      }>;
      readonly "fixedUrlParameters": Readonly<{
        readonly "liquidBodyVfx": "1";
        readonly "liquidSurfaceVfx": "1";
      }>;
    }>,
    Readonly<{
      readonly "name": "gas";
      readonly "code": 3;
      readonly "implemented": true;
      readonly "targetKind": "propagated-atmosphere-style-byte";
      readonly "executionProfile": Readonly<{
        readonly "detailScales": readonly [
          1,
          2,
          4,
        ];
        readonly "backend": "webgl";
        readonly "pipeline": "normal-hdr";
        readonly "variantZero": "pixel-preserving-baseline";
        readonly "fallbacks": Readonly<{
          readonly "classic": "disabled-preserve-baseline";
          readonly "canvas2d": "disabled-preserve-baseline";
          readonly "hdrUnavailable": "disabled-preserve-baseline";
          readonly "detail8x": "disabled-preserve-baseline";
        }>;
      }>;
      readonly "evidence": Readonly<{
        readonly "readerMethod": "atmosphereFieldAlpha";
        readonly "plane": "atmosphere-alpha";
      }>;
      readonly "fixedUrlParameters": Readonly<Record<string, never>>;
    }>,
    Readonly<{
      readonly "name": "emission";
      readonly "code": 4;
      readonly "implemented": true;
      readonly "targetKind": "semantic-material-id";
      readonly "executionProfile": Readonly<{
        readonly "detailScales": readonly [
          1,
          2,
          4,
        ];
        readonly "backend": "webgl";
        readonly "pipeline": "normal-hdr";
        readonly "variantZero": "pixel-preserving-baseline";
        readonly "fallbacks": Readonly<{
          readonly "classic": "disabled-preserve-baseline";
          readonly "canvas2d": "disabled-preserve-baseline";
          readonly "hdrUnavailable": "disabled-preserve-baseline";
          readonly "detail8x": "disabled-preserve-baseline";
        }>;
      }>;
      readonly "evidence": Readonly<{
        readonly "readerMethod": "emissionFieldAlpha";
        readonly "plane": "emission-alpha";
      }>;
      readonly "fixedUrlParameters": Readonly<Record<string, never>>;
    }>,
  ];
  readonly "captureDomainOrder": readonly [
    "gas",
    "liquid",
    "emission",
  ];
  readonly "normalHdrExecutionProfile": Readonly<{
    readonly "detailScales": readonly [
      1,
      2,
      4,
    ];
    readonly "backend": "webgl";
    readonly "pipeline": "normal-hdr";
    readonly "variantZero": "pixel-preserving-baseline";
    readonly "fallbacks": Readonly<{
      readonly "classic": "disabled-preserve-baseline";
      readonly "canvas2d": "disabled-preserve-baseline";
      readonly "hdrUnavailable": "disabled-preserve-baseline";
      readonly "detail8x": "disabled-preserve-baseline";
    }>;
  }>;
  readonly "fixtures": readonly [
    Readonly<{
      readonly "name": "showcase";
      readonly "scene": "showcase";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "gas";
          readonly "targets": null;
        }>,
        Readonly<{
          readonly "domain": "liquid";
          readonly "targets": null;
        }>,
        Readonly<{
          readonly "domain": "emission";
          readonly "targets": null;
        }>,
      ];
      readonly "preparationReportLabel": null;
      readonly "requirement": null;
    }>,
    Readonly<{
      readonly "name": "oil-motion";
      readonly "scene": "showcase";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "liquid";
          readonly "targets": readonly [
            8,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "prepareOilMotionVfxFixture";
      readonly "requirement": "--domain=liquid --target=8";
    }>,
    Readonly<{
      readonly "name": "water-motion";
      readonly "scene": "showcase";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "liquid";
          readonly "targets": readonly [
            2,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "prepareLiquidMotionVfxFixture";
      readonly "requirement": "--domain=liquid --target=2";
    }>,
  ];
  readonly "captureRecipes": readonly [
    Readonly<{
      readonly "name": "gas-showcase";
      readonly "domain": "gas";
      readonly "target": 0;
      readonly "fixture": "showcase";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "oxygen-showcase";
      readonly "domain": "gas";
      readonly "target": 4;
      readonly "fixture": "showcase";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "oil-motion";
      readonly "domain": "liquid";
      readonly "target": 8;
      readonly "fixture": "oil-motion";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "water-motion";
      readonly "domain": "liquid";
      readonly "target": 2;
      readonly "fixture": "water-motion";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
  ];
}>;
