// Generated by scripts/visual-static-contract-declarations.mjs. Do not edit.
export declare const VISUAL_CAPTURE_STATIC_CONTRACT: Readonly<{
  readonly "schema": "anifor.visual-capture.static-contract/v1";
  readonly "evidencePlanes": readonly [
    "atmosphere-alpha",
    "liquid-alpha",
    "emission-alpha",
    "powder-surface-alpha",
  ];
  readonly "drivers": readonly [
    Readonly<{
      readonly "name": "normal-hdr";
      readonly "domains": readonly [
        "gas",
        "liquid",
        "emission",
      ];
      readonly "framebufferAlphaPolicy": "exact";
      readonly "variants": readonly [
        Readonly<{
          readonly "name": "off";
          readonly "selection": 0;
          readonly "label": "OFF";
        }>,
        Readonly<{
          readonly "name": "a";
          readonly "selection": 1;
          readonly "label": "A";
        }>,
        Readonly<{
          readonly "name": "b";
          readonly "selection": 2;
          readonly "label": "B";
        }>,
      ];
    }>,
    Readonly<{
      readonly "name": "powder-render-style";
      readonly "domains": readonly [
        "powder",
      ];
      readonly "framebufferAlphaPolicy": "style-owned-nonempty";
      readonly "variants": readonly [
        Readonly<{
          readonly "name": "off";
          readonly "selection": "smooth";
          readonly "label": "Smooth";
        }>,
        Readonly<{
          readonly "name": "a";
          readonly "selection": "local";
          readonly "label": "Local";
        }>,
        Readonly<{
          readonly "name": "b";
          readonly "selection": "grains";
          readonly "label": "Grains";
        }>,
      ];
    }>,
  ];
  readonly "extensionDomains": readonly [
    Readonly<{
      readonly "name": "powder";
      readonly "targetKind": "none";
      readonly "driver": "powder-render-style";
      readonly "executionProfile": Readonly<{
        readonly "detailScales": readonly [
          1,
          2,
          4,
        ];
        readonly "backend": "webgl";
        readonly "pipeline": "normal-hdr";
        readonly "variantZero": "pixel-preserving-baseline";
        readonly "fallbacks": Readonly<{
          readonly "classic": "disabled-preserve-baseline";
          readonly "canvas2d": "disabled-preserve-baseline";
          readonly "hdrUnavailable": "disabled-preserve-baseline";
          readonly "detail8x": "disabled-preserve-baseline";
        }>;
      }>;
      readonly "evidence": Readonly<{
        readonly "plane": "powder-surface-alpha";
      }>;
      readonly "fixedUrlParameters": Readonly<Record<string, never>>;
    }>,
  ];
  readonly "fixtures": readonly [
    Readonly<{
      readonly "name": "powder-style-atlas";
      readonly "scene": "showcase";
      readonly "driver": "powder-render-style";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "powder";
          readonly "targets": readonly [
            0,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "preparePowderStyleAtlasFixture";
      readonly "requirement": "--domain=powder --target=0";
    }>,
  ];
  readonly "captureRecipes": readonly [
    Readonly<{
      readonly "name": "powder-style-atlas";
      readonly "domain": "powder";
      readonly "target": 0;
      readonly "fixture": "powder-style-atlas";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
  ];
}>;

export type VisualCaptureEvidencePlane = (
  typeof VISUAL_CAPTURE_STATIC_CONTRACT.evidencePlanes[number]
);
