// Generated by scripts/visual-static-contract-declarations.mjs. Do not edit.
export declare const VISUAL_CAPTURE_STATIC_CATALOG: Readonly<{
  readonly "schema": "anifor.visual-capture.static-catalog/v1";
  readonly "fixtures": readonly [
    Readonly<{
      readonly "name": "showcase";
      readonly "scene": "showcase";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "gas";
          readonly "targets": null;
        }>,
        Readonly<{
          readonly "domain": "liquid";
          readonly "targets": null;
        }>,
        Readonly<{
          readonly "domain": "emission";
          readonly "targets": null;
        }>,
      ];
      readonly "preparationReportLabel": null;
      readonly "requirement": null;
      readonly "driver": "normal-hdr";
    }>,
    Readonly<{
      readonly "name": "oil-motion";
      readonly "scene": "showcase";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "liquid";
          readonly "targets": readonly [
            8,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "prepareOilMotionVfxFixture";
      readonly "requirement": "--domain=liquid --target=8";
      readonly "driver": "normal-hdr";
    }>,
    Readonly<{
      readonly "name": "water-motion";
      readonly "scene": "showcase";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "liquid";
          readonly "targets": readonly [
            2,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "prepareLiquidMotionVfxFixture";
      readonly "requirement": "--domain=liquid --target=2";
      readonly "driver": "normal-hdr";
    }>,
    Readonly<{
      readonly "name": "powder-style-atlas";
      readonly "scene": "showcase";
      readonly "driver": "powder-render-style";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "powder";
          readonly "targets": readonly [
            0,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "preparePowderStyleAtlasFixture";
      readonly "requirement": "--domain=powder --target=0";
    }>,
    Readonly<{
      readonly "name": "material-lighting-atlas";
      readonly "scene": "showcase";
      readonly "driver": "material-lighting-profile";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "material-lighting";
          readonly "targets": readonly [
            0,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "prepareMaterialLightingAtlasFixture";
      readonly "requirement": "--domain=material-lighting --target=0";
    }>,
    Readonly<{
      readonly "name": "gas-material-lighting-atlas";
      readonly "scene": "showcase";
      readonly "driver": "material-lighting-profile";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "material-lighting";
          readonly "targets": readonly [
            0,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "prepareGasMaterialLightingAtlasFixture";
      readonly "requirement": "--domain=material-lighting --target=0";
    }>,
    Readonly<{
      readonly "name": "solid-material-lighting-atlas";
      readonly "scene": "showcase";
      readonly "driver": "material-lighting-profile";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "material-lighting";
          readonly "targets": readonly [
            0,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "prepareSolidMaterialLightingAtlasFixture";
      readonly "requirement": "--domain=material-lighting --target=0";
    }>,
    Readonly<{
      readonly "name": "multi-metal-material-lighting-atlas";
      readonly "scene": "showcase";
      readonly "driver": "material-lighting-profile";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "material-lighting";
          readonly "targets": readonly [
            0,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "prepareMultiMetalMaterialLightingAtlasFixture";
      readonly "requirement": "--domain=material-lighting --target=0";
    }>,
    Readonly<{
      readonly "name": "source-target-material-lighting-atlas";
      readonly "scene": "showcase";
      readonly "driver": "material-lighting-profile";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "material-lighting";
          readonly "targets": readonly [
            0,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "prepareSourceTargetGraphicsAuditFixture";
      readonly "requirement": "--domain=material-lighting --target=0";
    }>,
    Readonly<{
      readonly "name": "force-activity-material-lighting-atlas";
      readonly "scene": "showcase";
      readonly "driver": "material-lighting-profile";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "material-lighting";
          readonly "targets": readonly [
            0,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "prepareForceActivityGraphicsAuditFixture";
      readonly "requirement": "--domain=material-lighting --target=0";
    }>,
    Readonly<{
      readonly "name": "thermal-source-material-lighting-atlas";
      readonly "scene": "showcase";
      readonly "driver": "material-lighting-profile";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "material-lighting";
          readonly "targets": readonly [
            0,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "prepareCeramicTemperatureVfxFixture";
      readonly "requirement": "--domain=material-lighting --target=0";
    }>,
    Readonly<{
      readonly "name": "opposed-source-material-lighting-atlas";
      readonly "scene": "showcase";
      readonly "driver": "material-lighting-profile";
      readonly "constraints": readonly [
        Readonly<{
          readonly "domain": "material-lighting";
          readonly "targets": readonly [
            0,
          ];
        }>,
      ];
      readonly "preparationReportLabel": "preparePowderLightVfxFixture";
      readonly "requirement": "--domain=material-lighting --target=0";
    }>,
  ];
  readonly "captureRecipes": readonly [
    Readonly<{
      readonly "name": "gas-showcase";
      readonly "domain": "gas";
      readonly "target": 0;
      readonly "fixture": "showcase";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "oxygen-showcase";
      readonly "domain": "gas";
      readonly "target": 4;
      readonly "fixture": "showcase";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "oil-motion";
      readonly "domain": "liquid";
      readonly "target": 8;
      readonly "fixture": "oil-motion";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "water-motion";
      readonly "domain": "liquid";
      readonly "target": 2;
      readonly "fixture": "water-motion";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "powder-style-atlas";
      readonly "domain": "powder";
      readonly "target": 0;
      readonly "fixture": "powder-style-atlas";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "material-lighting-atlas";
      readonly "domain": "material-lighting";
      readonly "target": 0;
      readonly "fixture": "material-lighting-atlas";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "gas-material-lighting-atlas";
      readonly "domain": "material-lighting";
      readonly "target": 0;
      readonly "fixture": "gas-material-lighting-atlas";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "solid-material-lighting-atlas";
      readonly "domain": "material-lighting";
      readonly "target": 0;
      readonly "fixture": "solid-material-lighting-atlas";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "multi-metal-material-lighting-atlas";
      readonly "domain": "material-lighting";
      readonly "target": 0;
      readonly "fixture": "multi-metal-material-lighting-atlas";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "source-target-material-lighting-atlas";
      readonly "domain": "material-lighting";
      readonly "target": 0;
      readonly "fixture": "source-target-material-lighting-atlas";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "force-activity-material-lighting-atlas";
      readonly "domain": "material-lighting";
      readonly "target": 0;
      readonly "fixture": "force-activity-material-lighting-atlas";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "thermal-source-material-lighting-atlas";
      readonly "domain": "material-lighting";
      readonly "target": 0;
      readonly "fixture": "thermal-source-material-lighting-atlas";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
    Readonly<{
      readonly "name": "opposed-source-material-lighting-atlas";
      readonly "domain": "material-lighting";
      readonly "target": 0;
      readonly "fixture": "opposed-source-material-lighting-atlas";
      readonly "gain": 1;
      readonly "renderScale": 2;
    }>,
  ];
}>;
export declare const VISUAL_CAPTURE_STATIC_FIXTURES: typeof VISUAL_CAPTURE_STATIC_CATALOG.fixtures;
export declare const VISUAL_CAPTURE_STATIC_RECIPES: typeof VISUAL_CAPTURE_STATIC_CATALOG.captureRecipes;
